import Cutlery from '@/components/Cutlery/Cutlery';
import {string, z} from 'zod';

export const createEmployeeValidationSchema = z.object({
  fullname: z
    .string({required_error: 'Name is required'})
    .min(2, {message: 'Name must be at least 2 characters long'}),
  phoneNo: z
    .string({required_error: 'Phone number is required'})
    .min(10, {message: 'Phone number must be at least 10 characters long'}),
  secondaryPhoneNo: z.string().optional(),
  email: z.string().email().optional(),
  address: z
    .string({required_error: 'address is required'})
    .min(2, {message: 'address is required'}),
  caterorId: z.string().optional(),
  password: z.string({required_error: 'Password is required'}).optional(),
  isCounter: z.string().optional(),
});

export const employeeSettingValidationSchema = z.object({
  employeeId: z.string().optional(),

  // Main Routes
  eventPage: z.string().optional(),
  clientPage: z.string().optional(),
  packagePage: z.string().optional(),
  reportsPage: z.string().optional(),
  dishPage: z.string().optional(),
  settingPage: z.string().optional(),
  maharajPage: z.string().optional(),
  utensilPage: z.string().optional(),
  disposalPage: z.string().optional(),
  addonServicePage: z.string().optional(),
  foodVendorPage: z.string().optional(),
  incomeExpenditurePage: z.string().optional(),
  notificationDishPage: z.string().optional(),
  expenseMasterPage: z.string().optional(),
  vendorPage: z.string().optional(),
  employeeSettingPage: z.string().optional(),
  createPackagePage: z.string().optional(),
  displayPackagePage: z.string().optional(),
  rawMaterialCategoryPage: z.string().optional(),
  rawMaterialPage: z.string().optional(),
  rawMaterialProcessPage: z.string().optional(),
  dishCategoryPage: z.string().optional(),
  createDishPage: z.string().optional(),
  allDishesPage: z.string().optional(),
  paymentDetailsPage: z.string().optional(),
  termsConditionsPage: z.string().optional(),
  vendorRolePage: z.string().optional(),
  websiteContentPage: z.string().optional(),
  imageUploadPage: z.string().optional(),
  utensilCategoryPage: z.string().optional(),
  createUtensilsPage: z.string().optional(),
  utensilsInventoryPage: z.string().optional(),
  disposalCategoryPage: z.string().optional(),
  createDisposalPage: z.string().optional(),
  disposalInventoryPage: z.string().optional(),
  createEmployeePage: z.string().optional(),
  subEventPage: z.string().optional(),
  eventRateListPage: z.string().optional(),
  quotation: z.string().optional(),
  rawmaterialCalculator: z.string().optional(),
  rawMaterialOrder: z.string().optional(),
  dishProcess: z.string().optional(),
  eventDisposals: z.string().optional(),
  eventUtensils: z.string().optional(),
  afterEvent: z.string().optional(),
  bill: z.string().optional(),
  headerIncomeExpense: z.string().optional(),
  peopleCheck: z.string().optional(),
  westageReport: z.string().optional(),
  rawMaterialReturn: z.string().optional(),
  utensilChecking: z.string().optional(),
  afterEventDisposal: z.string().optional(),
  vehiclepage: z.string().optional(),
  cutlerypage: z.string().optional(),
  crmprocesspage: z.string().optional(),
  crmdashboardpage: z.string().optional(),
  dresscodepage: z.string().optional(),
  counterpage: z.string().optional(),
  utensilpeoplepage: z.string().optional(),
  disposalpeoplepage: z.string().optional(),
  cutlerycategorypage: z.string().optional(),
  mastercutlerypage: z.string().optional(),
  rawmaterialvendorpage: z.string().optional(),
  displayvendorpage: z.string().optional(),
  disposalvendorpage: z.string().optional(),
  dishCountandRMOrder: z.string().optional(),
  storeInventory: z.string().optional(),
  inwordStore: z.string().optional(),
  outwordStore: z.string().optional(),
  inwordHistory: z.string().optional(),
  outwordHistory: z.string().optional(),
  pendingBillReport: z.string().optional(),
  storeReport: z.string().optional(),
  wastageReport: z.string().optional(),
  disposalReport: z.string().optional(),
  utensilsReport: z.string().optional(),
  fuelMaster: z.string().optional(),
  banquetpage: z.string().optional(),
});
